//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace GoogleVoice.SampleData.SampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleDataSource { }
#else

	public class SampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/GoogleVoice;component/SampleData/SampleDataSource/SampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Conversations _Conversations = new Conversations();

		public Conversations Conversations
		{
			get
			{
				return this._Conversations;
			}
		}

		private double _UnreadCount = 0;

		public double UnreadCount
		{
			get
			{
				return this._UnreadCount;
			}

			set
			{
				if (this._UnreadCount != value)
				{
					this._UnreadCount = value;
					this.OnPropertyChanged("UnreadCount");
				}
			}
		}
	}

	public class Conversations : System.Collections.ObjectModel.ObservableCollection<ConversationsItem>
	{ 
	}

	public class ConversationsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _LastMessageTimeText = string.Empty;

		public string LastMessageTimeText
		{
			get
			{
				return this._LastMessageTimeText;
			}

			set
			{
				if (this._LastMessageTimeText != value)
				{
					this._LastMessageTimeText = value;
					this.OnPropertyChanged("LastMessageTimeText");
				}
			}
		}

		private string _LastMessageText = string.Empty;

		public string LastMessageText
		{
			get
			{
				return this._LastMessageText;
			}

			set
			{
				if (this._LastMessageText != value)
				{
					this._LastMessageText = value;
					this.OnPropertyChanged("LastMessageText");
				}
			}
		}

		private string _OtherParticipant = string.Empty;

		public string OtherParticipant
		{
			get
			{
				return this._OtherParticipant;
			}

			set
			{
				if (this._OtherParticipant != value)
				{
					this._OtherParticipant = value;
					this.OnPropertyChanged("OtherParticipant");
				}
			}
		}

		public bool IsRead
		{
			get;
			set;
		}
	}
#endif
}
